# Generated by Django 5.2.8 on 2026-03-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirlux', '0017_merge_20260319_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriamenu',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriamenu',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='menus/categorias/'),
        ),
    ]
